version: 2.0
jobs:
  build:
    docker:
      - image: wodby/drupal-php:7.4-4.17.1
      - image: wodby/mariadb:10.4-3.8.5
        environment:
          MYSQL_ROOT_PASSWORD: lilengine
          MYSQL_DATABASE: default
      - image: wodby/nginx:1.19-5.10.2
        environment:
          NGINX_SERVER_ROOT: /home/wodby/project
    steps:
      - checkout
      # Setup Environment Variables
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$PATH:$HOME/project/vendor/bin" >> $BASH_ENV
      # Import database
      - run:
          command: |
            wget https://github.com/datacharmer/test_db/blob/master/employees.sql db.sql
            mysql -u root -p lilengine default < db.sql
      # End import database
      # Check standard coding
      - run: phpcs web/core/modules/ban -vvv
      # Install composer
      - run: composer install
