version: 2.0
jobs:
  build:
    docker:
      - image: wodby/drupal-php:7.4-4.17.1
    steps:
      - checkout
      # Setup Environment Variables
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$PATH:$HOME/project/vendor/bin" >> $BASH_ENV
      - run: composer install
      - run: phpcs web/core/modules/action
