version: 2.0
jobs:
  build:
    docker:
      - image: circleci/php:7.4.5-apache-buster
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: default
          MYSQL_ROOT_PASSWORD: lilengine
    steps:
      - checkout

