version: 2.0
jobs:
  build:
    docker:
      - image: drupal:9.0.3-apache
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: default
          MYSQL_ROOT_PASSWORD: lilengine
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run:
          name: Symlink
          command: |
            apt update
            apt install git -y
            chmod -R 777 /root
            chown -R www-data:www-data /root
            rm -rf /var/www/html
            ln -s /root/project/web/ /var/www/html
      # Setup Environment Variables
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$PATH:$HOME/project/vendor/bin" >> $BASH_ENV
      - run: cd /root/project
      # End import database
      # Install composer
      - run: composer install
      - run: drush si standard --db-url=mysql://root:lilengine@127.0.0.1/default --account-pass="admin"
      # Check standard coding
      #- run: phpcs web/modules/custom  -vvv
      - run: drush status
      - run: /etc/init.d/apache2 start
      - run: curl http://localhost
      - run: drush cr
      - run: phpunit web/modules/custom/lilengine_automated_test/tests/src/ExistingSiteJavascript

