version: 2.0
jobs:
  build:
    docker:
      - image: circleci/php:7.4.7-apache-buster
    steps:
      - checkout
      # Setup Environment Variables
      - run:
          name: Enable some PHP extentions
          command: |
            docker-php-ext-install gd
            docker-php-ext-enable gd
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$PATH:$HOME/project/vendor/bin" >> $BASH_ENV
      - run: composer install
      - run: phpcs web/core/modules/action
